### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by vercingetorx** [SciNim/impulse#2]
I am looking to implement some image hashing in Nim, specifically PHash and would like to use this library. However the readme suggests the project is unfinished. Can someone clarify?

**Comment by mratsim** [comment]
I have been researching techniques to significantly accelerate image and signal processing in [Laser](https://github.com/numforge/laser) in particular:
- Convolution: https://github.com/numforge/laser/blob/master/research/convolution_optimisation_resources.md
- Nested loops: https://github.com/numforge/laser/blob/master/research/automatic_loop_nest_scheduling.md

This repo is the start of productionizing that research.
The idea is to provide a front-end agnostic optimized backend for signal and image processing.

For now there is FFT implemented https://github.com/SciNim/impulse/blob/26e25e7/impulse/fft/pocketfft.nim#L302-L339
but there is no official API because I'm unsure of what kind of API to provide in particular I want it to be flexible enough for any image, tensor, matrix libraries out there.

Now, how can we work:

Tell me the algorithm you need, and potentially the kind of API or and/or your backend data structure for example is it:
```Nim
type Image = object
  ## RGB image
  height, width: int
  data: seq[tuple[r, g, b: uint8]]
```
or something more complex like images for video encoding (https://github.com/mratsim/trace-of-radiance/blob/e928285/trace_of_radiance/io/h264.nim#L20-L25)
```Nim
  Frame = ptr object
    ## YUV / YCbCr image as used in  videos
    Y: ptr UncheckedArray[uint8]
    Cb, Cr: ptr UncheckedArray[uint8]
    lumaWidth, lumaHeight: int32
    size: int32
    buffer: UncheckedArray[uint8]
```

Depending on the complexity and my availability, I may be able to implement it, wrap something or give pointers so that someone or you can take that over.

**Comment by vercingetorx** [comment]
Thanks for the reply. My initial goal is to implement pHash (and hamming distance) using this library as a model https://github.com/JohannesBuchner/imagehash/blob/master/imagehash.py. Potentially expanding later on to accommodate other hashing algorithms (wave hash, average hash, etc).

```
def phash(image, hash_size=8, highfreq_factor=4):
	"""
	Perceptual Hash computation.
	Implementation follows http://www.hackerfactor.com/blog/index.php?/archives/432-Looks-Like-It.html
	@image must be a PIL instance.
	"""
	if hash_size < 2:
		raise ValueError("Hash size must be greater than or equal to 2")

	import scipy.fftpack
	img_size = hash_size * highfreq_factor
	image = image.convert("L").resize((img_size, img_size), Image.ANTIALIAS)
	pixels = numpy.asarray(image)
	dct = scipy.fftpack.dct(scipy.fftpack.dct(pixels, axis=0), axis=1)
	dctlowfreq = dct[:hash_size, :hash_size]
	med = numpy.median(dctlowfreq)
	diff = dctlowfreq > med
	return ImageHash(diff)
```

As far as the data structure, rgb and greyscale would be the goal using one of the Nim image manipulation libraries similar to PIL.

**Comment by mratsim** [comment]
So FFT can indeed be used for DCT, it's tested with scipy example and should give the same result:

https://github.com/SciNim/impulse/blob/26e25e701be75446ad2b91403a4538465f44f1b5/impulse/fft/pocketfft.nim#L322-L339

So I have to export and document how to use it. Note that I use raw pointers so that it works with any seq/Matrix/Tensor/image type.
It's also low-level so you might want to build an abstraction between your type and the descriptors.

**Comment by vercingetorx** [comment]
Thanks for the input. Think I'll roll up my sleeves and give it a try.
